fix: use github token in update libs workflow
canonical/oathkeeper-operator pull request #66
Opened 2024-04-17 08:03 UTC by natalian98

This PR fixes the workflow error `Resource not accessible by personal access token` by using `GITHUB_TOKEN` instead of `PAT_TOKEN`.

2024-04-17 08:11 UTC, BarcoMasile approved these changes

2024-04-17 08:51 UTC, BarcoMasile approved these changes

2024-04-17 15:41 UTC, shipperizer requested changes
issue seems to be due to the token missing permissions to access this repo, i applied for a token change and that is pending approval

for the time being, let s block this

2024-04-22 15:20 UTC, natalian98 commented
Closing as the workflow was fixed by updating the token permissions

2024-04-22 15:20 UTC, closed without merging